# Example docker-compose.yml file for Taskpony.
# Copy this to a new directory and run "docker compose up -d" to fetch and run Taskpony on port 5000
# Updates to Taskpoint can be applied by "docker compose down && docker compose pull & docker compose up -d"

services:

  taskpony:
    image: 'digdilem/taskpony:latest'
    container_name: taskpony
    ports:
      - "5000:5000"
    volumes:  
      # We need a persistent directory mounted in order to save our tasks database. 
      - ./data:/opt/taskpony/db
    restart: unless-stopped

# End of file

