# Example docker-compose.yml file for Taskpony.
# Copy this to a new directory and run "docker compose up -d" to fetch and run Taskpony on port 5000
# Updates to Taskpoint can be applied by "docker compose down && docker compose up -d"

services:

  taskpony:
    image: 'digdilem/taskpony:latest'
    ports:
      - "5000:5000"
    volumes:  
      # We need a persistent directory mounted in order to save our tasks database. This example uses ./data under this file to do so. It will be autocreated.
      - ./data:/opt/tasks
    restart: unless-stopped

# End of file

