blank_issues_enabled: false
<<<<<<< HEAD
=======
contact_links:
  - name: ğŸ’¬ Discussions
    url: https://github.com/digdilem/taskpony/discussions
    about: Ask questions or discuss ideas
>>>>>>> 3d6f2eb (Add github forms)
