blank_issues_enabled: false
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
contact_links:
  - name: ğŸ’¬ Discussions
    url: https://github.com/digdilem/taskpony/discussions
    about: Ask questions or discuss ideas
>>>>>>> 3d6f2eb (Add github forms)
=======
>>>>>>> 55aab08 (Add github forms-b)
=======
>>>>>>> github/main
